from typing import Annotated, List, TypedDict, Union, Dict, Any
from datetime import datetime
from langchain_core.documents import Document
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

class GraphState(TypedDict):
    """
    Represents the state of our RAG graph.
    """
    # The user's input question
    question: str
    
    # The target date for point-in-time retrieval (Hard filter)
    target_date: datetime
    
    # The list of retrieved documents from the vector store
    context: List[Document]
    
    # The final answer generated by the LLM
    answer: str
    
    # Quantitative Views from Committees
    # Dict mapping factor_theme -> {q_value, omega_value, reasoning}
    committee_views: Dict[str, Any]
    
    # Optional: target factor for analysis (default: "value")
    target_factor: str
    
    # Conversation history (accumulated)
    messages: Annotated[List[BaseMessage], add_messages]

    # Performance and Phase State
    cumulative_return: float  # Cumulative return for path-dependency
    is_training: bool        # Flag to indicate training vs test mode
    
    # Self-Evolution State
    actual_return: float      # Observed factor return for the period
    reflections: Dict[str, Any] # Detailed reflection reasoning for each committee
