from typing import Annotated, List, TypedDict, Union, Dict, Any
from datetime import datetime
from langchain_core.documents import Document
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

def add_reflections(left: Dict[str, Any], right: Dict[str, Any]) -> Dict[str, Any]:
    """Reducer to merge reflections from parallel nodes."""
    if not left:
        return right
    if not right:
        return left
    return {**left, **right}

class GraphState(TypedDict):
    """
    Represents the state of our RAG graph.
    """
    # The user's input question
    question: str
    
    # The target date for point-in-time retrieval (Hard filter)
    target_date: datetime
    
    # The list of retrieved documents from the vector store
    context: List[Document]
    
    # The final answer generated by the LLM
    answer: str
    
    # Quantitative Views from Committees
    # Dict mapping factor_theme -> {q_value, omega_value, reasoning}
    committee_views: Dict[str, Any]
    
    # Factor Regime Data per committee
    regime_data: Dict[str, Any]

    # Optional: target factor for analysis (default: "value")
    target_factor: str

    # Today's daily summary fetched from MongoDB
    daily_summary: str
    
    # Conversation history (accumulated)
    messages: Annotated[List[BaseMessage], add_messages]

    # Performance and Phase State
    cumulative_return: float  # Cumulative return for path-dependency
    is_training: bool        # Flag to indicate training vs test mode
    
    # Self-Evolution State
    # Observed factor returns for the period (mapping factor name to return)
    actual_returns: Dict[str, float]
    # Detailed reflection reasoning for each committee
    reflections: Annotated[Dict[str, Any], add_reflections]
