from typing import Annotated, List, TypedDict, Union
from datetime import datetime
from langchain_core.documents import Document
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

class GraphState(TypedDict):
    """
    Represents the state of our RAG graph.
    """
    # The user's input question
    question: str
    
    # The target date for point-in-time retrieval (Hard filter)
    target_date: datetime
    
    # The list of retrieved documents from the vector store
    context: List[Document]
    
    # The final answer generated by the LLM
    answer: str
    
    # Conversation history (accumulated)
    messages: Annotated[List[BaseMessage], add_messages]
